-- colors
lexer.property['color.red']          = '#800000'
lexer.property['color.yellow']       = '#808000'
lexer.property['color.green']        = '#008000'
lexer.property['color.teal']         = '#008080'
lexer.property['color.purple']       = '#800080'
lexer.property['color.orange']       = '#B08000'
lexer.property['color.blue']         = '#000080'
lexer.property['color.black']        = '#000000'
lexer.property['color.grey']         = '#808080'
lexer.property['color.white']        = '#FFFFFF'

-- styles
lexer.property['style.nothing']      = ''
lexer.property['style.default']      = 'fore:$(color.black),back:$(color.white)'
lexer.property['style.linenumber']   = 'fore:$(color.black),back:#DCDCDC'
lexer.property['style.bracelight']   = '$(style.nothing)'
lexer.property['style.bracebad']     = '$(style.nothing)'
lexer.property['style.controlchar']  = '$(style.nothing)'
lexer.property['style.indentguide']  = '$(style.nothing)'
lexer.property['style.calltip']      = '$(style.nothing)'

lexer.property['style.whitespace']   = '$(style.nothing)'
lexer.property['style.comment']      = 'fore:#0000FF,italics'
lexer.property['style.string']       = 'fore:#CC0000'
lexer.property['style.number']       = 'fore:$(color.teal)'
lexer.property['style.keyword']      = 'fore:$(color.blue),bold'
lexer.property['style.identifier']   = '$(style.nothing)'
lexer.property['style.operator']     = 'fore:$(color.black),bold'
lexer.property['style.error']        = 'fore:#FF0000'
lexer.property['style.preprocessor'] = 'fore:$(color.green),bold'
lexer.property['style.constant']     = '$(style.keyword)'
lexer.property['style.variable']     = '$(style.label)'
lexer.property['style.function']     = '$(style.label)'
lexer.property['style.class']        = '$(style.nothing)'
lexer.property['style.type']         = 'fore:$(color.blue)'
lexer.property['style.label']        = 'fore:$(color.red)'
lexer.property['style.regex']        = '$(style.nothing)'
lexer.property['style.embedded']     = '$(style.nothing)'
